name: Auto-Labelling of Issues
#Constraints on when the label are changed
on:
  issues:
    types: [opened]

#Permissions for what needs to be authorized
permissions:
  contents: read
  issues: write

#Different jobs based on what should be done
jobs:
  label_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Adding Labels
        uses: actions/issue-labeler@v3
        with:
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          configuration-path: .github/labellerAction.yml
