name: Java CI

on:
  pull_request:
    branches:
      - dev

  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install dependencies
        run: mvn install

      - name: Run tests
        run: mvn test

      - name: Get changed Java files
        id: changed-files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.java$' || true > changed_files.txt
          echo "CHANGED_FILES=$(cat changed_files.txt)" >> $GITHUB_ENV

      - name: Print changed files
        run: |
          echo "Changed files:"
          cat changed_files.txt

      - name: Build and test changed files
        if: ${{ env.CHANGED_FILES != '' }}
        run: |
          for file in $(cat changed_files.txt); do
            echo "Processing $file..."
            # Ensure the file compiles
            javac "$file" || exit 1
            # Extract directory and classpath
            dir=$(dirname "$file")
            classname=$(basename "$file" .java)
            # Run the compiled class
            java -cp "$dir" "$classname" || exit 1
          done
