name: Java CI

on:
  pull_request:
    branches:
      - dev

  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full commit history is fetched

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install dependencies
        run: mvn install

      - name: Get changed Java files
        id: changed-files
        run: |
          echo "Detecting changed Java files..."
          base_ref=${{ github.event.pull_request.base.sha || 'origin/dev' }}
          echo "Comparing ${base_ref} with HEAD..."
          git diff --name-only "${base_ref}" HEAD | grep '\.java$' || true > changed_files.txt
          echo "CHANGED_FILES=$(cat changed_files.txt)" >> $GITHUB_ENV

      - name: Print changed files
        run: |
          echo "Changed files:"
          cat changed_files.txt

    outputs:
      changed_files: ${{ steps.changed-files.outputs.CHANGED_FILES }}

  test:
    needs: build
    runs-on: ubuntu-latest
    if: needs.build.result == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run tests
        run: mvn test

      - name: Test changed Java files
        run: |
          if [[ -z "${{ needs.build.outputs.changed_files }}" ]]; then
            echo "No changed Java files to test."
            exit 0
          fi
          echo "Testing changed Java files..."
          for file in $(cat changed_files.txt); do
            echo "Processing $file..."
            javac "$file" || exit 1
            dir=$(dirname "$file")
            classname=$(basename "$file" .java)
            echo "Running $classname..."
            java -cp "$dir" "$classname" || exit 1
          done
