name: Java CI

on:
  pull_request:
    branches:
      - dev

  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java environment
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: mvn install

      # Step 4: Run all tests
      - name: Run tests
        run: mvn test

      # Step 5: Detect changed `.java` files
      - name: Get changed Java files
        id: changed-files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.java$' || true > changed_files.txt
          echo "CHANGED_FILES=$(cat changed_files.txt)" >> $GITHUB_ENV

      # Step 6: Debugging changed files
      - name: Debug CHANGED_FILES
        run: |
          echo "Changed files from CHANGED_FILES: ${{ env.CHANGED_FILES }}"
          echo "Contents of changed_files.txt:"
          cat changed_files.txt

      # Step 7: Build and run changed `.java` files
      - name: Build and test changed files
        if: env.CHANGED_FILES != ''
        run: |
          echo "Building and testing changed Java files..."
          for file in $(cat changed_files.txt); do
            echo "Processing $file..."
            
            # Compile the file
            javac "$file" || exit 1

            # Determine the class name and directory
            dir=$(dirname "$file")
            classname=$(basename "$file" .java)

            # Run the compiled class (assumes no packages; adjust if needed)
            echo "Running $classname..."
            java -cp "$dir" "$classname" || exit 1
          done
